### PR TITLE
Fix #33 filter molecule_header, header or molecule_from_yaml missing

### LINKED ISSUE #33: Filter molecule_header & molecule_from_yaml missing
# ISSUE

Following filters are missing
- molecule_header
- molecule_from_yaml

Description
- `molecule create` it creates the ec2 instance, but fails to write the config to filesystem with the error `filter molecule_header` missing. so molecule doesn't know about the instance that's actually created. 
- `molecule destroy` This command does not destroy the instance, as the config was not written to filesystem by create method in the first place. One has to manually cleanup/destroy the ec2 instance.

## Steps to reproduce
```
molecule init role -d ec2 <rolename>
cd <rolename>
```
modify molecule.yaml eg:
```
---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: instance-1
    image: ami-0dd9f0e7df0f0a138
    instance_type: t2.micro
    vpc_subnet_id: subnet-b3a28af9
provisioner:
  name: ansible
verifier:
  name: ansible

```

```
$ molecule create 

PLAY [Create]

TASK [Dump instance config] ************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "template error while templating string: no filter named 'molecule_header'. String: {{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"}
```

```
$ molecule destroy

PLAY [Destroy] *************************************************************************************************************************************************************************************************

TASK [Populate instance config] ********************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "template error while templating string: no filter named 'molecule_from_yaml'. String: {{ lookup('file', molecule_instance_config) | molecule_from_yaml }}"}
```

## Expected Behavior
- `molecule create` should create the ec2 instance and write the config. 
- `molecule list` should list the instances
- `molecule destroy` should destroy the instances. 

## REASON
As of molecule v3, ansible molecule filters have been removed. 
- https://github.com/ansible-community/molecule/pull/2869
- https://github.com/ansible-community/molecule/releases/tag/3.1.1

## SOLUTION
- Removing those 2 filters from the generated code works. But this approach would require modifying every molecule generated role manually. 
- A better approach would be to modify the cookiecutter template.

### PR DESCRIPTION
**Pull request by aruntomar**
This PR fixes the issue https://github.com/ansible-community/molecule-ec2/issues/33

As of molecule v3, ansible molecule filters have been removed.
- ansible-community/molecule#2869
- https://github.com/ansible-community/molecule/releases/tag/3.1.1

### CODE REVIEW

**Comment by matusmalinka** [comment]
+1 for this commit
I've run into this issue few days ago.

**Review by ssbarnea — CHANGES_REQUESTED** [review]
This review is not complete as it needs other changes, like adding sh module dependency or replacing it.

Ping me on irc when ready.

**Comment by tbugfinder** [comment]
Hi @aruntomar ,
would it be possile to finalize it?
After that I'm asking to carve out a new release so that new users don't have to start with invalid configs.

**Comment by aruntomar** [comment]
hi @tbugfinder,

apologies for the delay. lately, I have been distracted and haven't focused. I'll try to fix it this weekend. 

Arun

**Comment by aruntomar** [comment]
@tbugfinder @ssbarnea  All checks passing now. kindly review.

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
