### PR TITLE
Add tag-based resource specification (AMI, VPC, subnet)

### PR DESCRIPTION
**Pull request by jgoldschrafe**
This change adds three new platform parameters, `image_filters`, `vpc_filters`, and `vpc_subnet_filters`, that can be used to look up resources by a tag specification. These are mostly helpful in multi-account environments where it's not necessarily clear what specific VPC subnet ID will be available in a given Molecule run's execution environment, but they can be tagged in a predictable way.

I fixed a couple other small issues with my last PR as I went through, mostly related to `default` filter semantics—the intent of those should be obvious, but happy to back those out and separate them if they complicate the review.

### CODE REVIEW

**Comment by tbugfinder** [comment]
LGTM 💯

**Comment by lod** [comment]
I've been using this set of code and it works well.

A few issues (as reported elsewhere) but not related to this change set.

**Comment by jgoldschrafe** [comment]
Hey folks, this one's been open for a hot minute. Any chance I could get either an approval on this or some feedback on what to change/assurances to add?

Thanks a lot!

**Comment by briantist** [comment]
@ssbarnea Hi Sorin, was wondering if this could get a review and perhaps get merged? Seems that 2 other community members were also looking forward to it and have looked at it previously. It would also unblock ansible-community/molecule-plugins#51 🙏

**Comment by ssbarnea** [comment]
This will need to be reopen against https://github.com/ansible-community/molecule-plugins/pull/36

**Pull request closed without merging**
